name: 2es
channels:
  - conda-forge
dependencies:
  - python=3.11
  # Core scientific stack
  - numpy>=1.20
  - pandas>=1.3
  - scipy>=1.7
  # Astronomy
  - astroquery>=0.4.6
  # Visualization
  - matplotlib>=3.4
  - seaborn>=0.11
  - plotly>=5.0
  # File / Excel
  - openpyxl>=3.0.7
  - xlsxwriter>=3.0.0
  # Utilities
  - tqdm>=4.60
  - ipywidgets>=8.1
  - voila>=0.5,<0.6
  # (Optional but often useful; uncomment if you rely on them)
  # - astropy
  # - pyarrow
  # If you need any pure pip-only packages:
  - pip
  - pip:
      # - some-pip-only-package==0.3.1

