name: 2es
channels:
  - conda-forge
dependencies:
  - python=3.11
  - numpy
  - pandas
  - scipy
  - astropy
  - astroquery
  - matplotlib
  - seaborn
  - plotly
  - openpyxl
  - xlsxwriter
  - tqdm
  - ipywidgets
  - voila
