name: 2es
channels:
  - conda-forge
dependencies:
  - python=3.11
  # Core scientific
  - numpy=1.26.*
  - pandas=2.2.*
  - scipy=1.13.*
  # Astronomy
  - astroquery=0.4.7
  - astropy=6.0.*
  # Visualization
  - matplotlib=3.8.*
  - seaborn=0.13.*
  - plotly=5.23.*
  # Excel / I/O
  - openpyxl=3.1.*
  - xlsxwriter=3.2.*
  # Utilities
  - tqdm=4.66.*
  - ipywidgets=8.1.*
  - voila=0.5.*
  # (Optional: uncomment if you later need faster parquet IO)
  # - pyarrow
  - pip
  - pip:
      # Add any truly pip-only packages below (leave empty list if none)
      # - some-extra-package==0.1.0
